services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "/var/log:/var/log:ro"
      - "/mnt:/mnt:ro"
    image: mawulib/monitor-backend:latest
    privileged: true
    networks:
      - app_network
    restart: on-failure:3

  log-manager:
    container_name: log-manager
    build:
      context: ./log-manager
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    image: mawulib/monitor-frontend:latest
    networks:
      - app_network
    restart: on-failure:3

networks:
  app_network:
    driver: bridge